[script:asset_inventory_assets]
match = /asset_inventory_workbench/asset_inventory_api/assets
script = app_access.py
handler = app_access.AssetInventoryAccessApp
handlertype = python
scripttype = persist
python.version = python3
passPayload = true
passHttpHeaders = true
capability =
requireAuthentication = true